name: "linuxptp-daemon: Prow github actions"
on:
  issue_comment:
    types: [created]

jobs:
  prow:
    uses: edcdavid-org/ptp-operator-upstream-monorepo/.github/workflows/_reusable-linuxptp-daemon-prow.yml@main
    secrets: inherit
